/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AOption: typeof import('@arco-design/web-vue')['Option']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASlider: typeof import('@arco-design/web-vue')['Slider']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    Bar: typeof import('./src/components/mobile/components/bar.vue')['default']
    Bill: typeof import('./src/components/mobile/bill.vue')['default']
    Chat: typeof import('./src/components/mobile/chat.vue')['default']
    Draw: typeof import('./src/components/mobile/image/draw.vue')['default']
    Header: typeof import('./src/components/mobile/layout/components/header.vue')['default']
    History: typeof import('./src/components/mobile/history.vue')['default']
    Image: typeof import('./src/components/mobile/image.vue')['default']
    Index: typeof import('./src/components/pc/Index.vue')['default']
    Layout: typeof import('./src/components/mobile/layout/index.vue')['default']
    Menu: typeof import('./src/components/pc/Menu.vue')['default']
    Paint: typeof import('./src/components/pc/Paint.vue')['default']
    Recharge: typeof import('./src/components/pc/Recharge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Set: typeof import('./src/components/mobile/image/set.vue')['default']
  }
}
